name: Player Stats Monitor

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Install PowerShell 7.4.1
        run: |
          wget https://github.com/PowerShell/PowerShell/releases/download/v7.4.1/powershell-7.4.1-linux-x64.tar.gz
          mkdir ~/powershell && tar -xvf ./powershell-7.4.1-linux-x64.tar.gz -C ~/powershell

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Run Tracker
        run: ~/powershell/pwsh "./PlayerStats.ps1"

      - name: Commit Log
        run: |
          git config --global user.name "IbraBot"
          git config --global user.email "ibra@example.com"
          git add NewStats.txt StatsHistory.txt
          git commit -m "Update lifetime and peak logs" || echo "No changes to commit"
          git push

      - name: Send Lifetime Log to Discord
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          message=$(awk 'NF' NewStats.txt | awk '{print}' ORS='\\n')
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$message\"}" \
               $DISCORD_WEBHOOK
