name: Lifetime Tracker

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 1 minute
  workflow_dispatch:       # 👈 Enables manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Install PowerShell 7.5.2 Preview
        run: |
          wget https://github.com/PowerShell/PowerShell/releases/download/v7.5.2-preview/powershell-7.5.2-preview-linux-x64.tar.gz
          mkdir ~/powershell
          tar -xvf ./powershell-7.5.2-preview-linux-x64.tar.gz -C ~/powershell
          sudo ln -s ~/powershell/pwsh /usr/bin/pwsh

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Tracker
        run: pwsh "./TotalLifetimePlayers.ps1"

      - name: Configure Git
        run: |
          git config user.name "IbraBot"
          git config user.email "ibra@example.com"

      - name: Commit Log
        run: |
          git add lifetime_log.txt
          git commit -m "Update lifetime count"
          git push
