name: Send New Players Chart to Discord

on:
  workflow_dispatch:

jobs:
  send-newplayers-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Run NewPlayersChart.ps1
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: pwsh ./NewPlayersChart.ps1 -Slots 18
