name: New Players Chart

on:
  workflow_dispatch:

jobs:
  send-newplayers-chart:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 🔍 Check and Install ImageMagick if Missing
        shell: pwsh
        run: |
          if (-not (Get-Command magick -ErrorAction SilentlyContinue)) {
          Write-Host "🛠 ImageMagick not found. Installing via Chocolatey..."
          choco install imagemagick -y
          } else {
          Write-Host "✅ ImageMagick already installed. Skipping install."
          }

      - name: Run NewPlayersChart.ps1
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: pwsh ./NewPlayersChart.ps1
